[build]
    functions = "functions"
    node_bundler = "esbuild"

[[redirects]]
    force = true
    from = "https://hoctuvung3.netlify.app/api/*"
    status = 200
    to = "https://hoctuvung3.netlify.app/.netlify/functions/api/:splat"
